# Generated by Django 4.1.5 on 2023-02-06 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_payment_use_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_release',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 20, 17, 27, 267626), editable=False),
        ),
    ]
