# Generated by Django 4.1.5 on 2023-02-06 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_payment_payment_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_release',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
