# Generated by Django 4.1.5 on 2023-02-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_payment_payment_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_release',
        ),
    ]
