# Generated by Django 4.1.5 on 2023-02-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_payment_payment_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phonenumber',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
