# Generated by Django 4.2.2 on 2023-06-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
